version: '3.5'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-thucdb}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-thucpassword}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: unless-stopped

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=thuc
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  redis_data:
    driver: local
